apache/ozone-docker-runner

.asf.yaml, .github/pull_request_template.md, .github/workflows/build.yaml, CONTRIBUTING.md, README.md, SECURITY.md
This PR contains basic cleanup after moving out the source of `apache/ozone-runner` to this repository.
Basic Github action workflow + standard descriptors (PR template, notification) + README update.
=> HDDS-4795. Separate source of Ozone container images to different repositories

Dockerfile
Pre-install `awscli` in the `ozone-runner` docker image to save some execution time in acceptance tests.
https://issues.apache.org/jira/browse/HDDS-4881
Built the image locally:
docker build -t apache/ozone-runner:dev .
executed some Ozone acceptance test:
cd ozone/hadoop-ozone/dist/target/ozone-1.1.0-SNAPSHOT/compose/ozone
OZONE_RUNNER_VERSION=dev ./test.sh
and verified in `result/robot*xml` that `awscli` no longer has to be installed during acceptance test:
Running command 'sudo -E yum install -y awscli 2&gt;&amp;1'.
Package awscli-1.14.28-5.el7_5.1.noarch already installed and latest version
=> HDDS-4881. Pre-install awscli in ozone-runner

Dockerfile
Async Profiler default output format is being changed in HDDS-5009 to one not supported by version 1.5.  We need to bump the version being installed in the image.
https://issues.apache.org/jira/browse/HDDS-5025
Built the image and ran the changes in https://github.com/apache/ozone/pull/2078 with it.
```
scm_1       | 2021-03-24 09:00:59,907 [qtp2054997292-347] INFO http.ProfileServlet: Servlet process PID: 7 asyncProfilerHome: /opt/profiler
scm_1       | 2021-03-24 09:00:59,922 [qtp2054997292-347] INFO http.ProfileServlet: Running command async: [/opt/profiler/profiler.sh, -e, cpu, -d, 10, -o, flamegraph, -f, /tmp/prof-output/async-prof-pid-7-cpu-1.html, 7]
scm_1       | Profiling started
scm_1       | Profiling for 10 seconds
scm_1       | 2021-03-24 09:01:10,603 [qtp2054997292-342] INFO …
```
=> HDDS-5025. Upgrade Async Profiler

Dockerfile
JIRA: https://issues.apache.org/jira/browse/HDDS-5231
We can update to the `OZONE_` prefixes to avoid the following warnings. 
```
WARNING: HADOOP_CONF_DIR has been deprecated by OZONE_CONF_DIR.
WARNING: HADOOP_LOG_DIR has been deprecated by OZONE_LOG_DIR.
```
=> HDDS-5231. replace HADOOP_ with OZONE_ prefix in the ozone-runner docker image

Dockerfile
Fix the error:
```
...
Step 2/45 : RUN GO111MODULE=off go get -u github.com/rexray/gocsi/csc
---> Running in 8e018058512a
src/golang.org/x/net/http2/transport.go:417:45: undefined: os.ErrDeadlineExceeded
The command '/bin/sh -c GO111MODULE=off go get -u github.com/rexray/gocsi/csc' returned a non-zero code: 2
```
by upgrading `go`.
https://issues.apache.org/jira/browse/HDDS-6023
Built the image locally, ran `ozone-csi` smoketest with it.
CI:
https://github.com/adoroszlai/ozone-docker-runner/runs/4274790893
=> HDDS-6023. Cannot rebuild ozone-runner due to undefined: os.ErrDeadlineExceeded

Dockerfile
Upgrade `pip` in `ozone-runner` Docker image to avoid:
```
$ cd hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone-om-ha
$ docker-compose build
...
=> ERROR [15/21] RUN sudo pip3 install robotframework-sshlibrary
...
executor failed running [/bin/sh -c sudo pip3 install robotframework-sshlibrary]: exit code: 1
ERROR: Service 'datanode' failed to build : Build failed
```
https://issues.apache.org/jira/browse/HDDS-5967
Built `ozone-runner` locally:
```
$ docker build -t apache/ozone-runner:HDDS-5967 .
...
=> [stage-2  4/31] RUN sudo python3 -m pip install --upgrade pip
...
=> => naming to docker.io/apache/ozone-runner:HDDS-5967
```
and used it to build temporary images for `ozone-om-ha` environment:
```
$ export OZONE_RUNNER_VERSION=HDDS-5967
$ cd …
```
=> HDDS-5967. Upgrade pip in ozone-runner

Dockerfile
- Bump golang base image to [1.17.6](https://hub.docker.com/_/golang?tab=tags&page=1&name=1.17) (was 1.17.3)
- Bump centos base image to [7.9.2009](https://hub.docker.com/_/centos?tab=tags&page=1&name=7.9) (was [7.6.1810](https://hub.docker.com/_/centos?tab=tags&page=1&name=7.6))
- ~~Incorporated [HDDS-6239](https://github.com/apache/ozone/pull/3029) into Dockerfile (centos vault repo url change). `yum install` will fail without it.~~ no longer the case as centos 7 is not EOL, unlike centos 8.
- Remove unused dependencies `bzip2-devel`, `gcc48-c++`, `lz4-devel`, `snappy-devel`, `zlib-devel`, `git` in second stage (stage 1).
- Bump `gflags` to [2.2.2](https://github.com/gflags/gflags/releases) (was 2.0.0)
- Bump `zstd` to [1.5.2](https://github.com/facebook/zstd/releases) (was 1.1.3)
- …
=> HDDS-6264. Bump centos to 7.9.2009, dependencies and tools in ozone-runner

Dockerfile
Install JDK instead of JRE in `ozone-runner` image, e.g. to be able to take heap/stack dumps.
https://issues.apache.org/jira/browse/HDDS-6359
https://github.com/adoroszlai/ozone-docker-runner/runs/5276229639#step:3:4047
=> HDDS-6359. Install JDK in runner image

.github/workflows/build.yaml, Dockerfile, README.md
- Bump rocksdb ldb to 7.0.3
- Bump gcc/g++ from 4 to 10 as rocksdb 7.x now requires gdb >= 7 to be compiled
- I tried to bump g++ to 11 but CentOS 7 repo, for whatever reason, doesn't have one packaged for arm64 right now. g++ 10 also works fine as I tested.
- https://pkgs.org/download/devtoolset-10-gcc-c++
- https://pkgs.org/download/devtoolset-11-gcc-c++
- Bump golang from 1.17.7 to 1.17.8
- 1.18.0 has some issues when compiling `goofys` from source in arm64 env.
- ~~And changed to alpine image from buster to save 100 MB download.~~ Turns out go uses Alpine's musl libc this way which causes compatiblity issue with CentOS. And `musl-libc` [doesn't seem to have an arm64 package](https://pkgs.org/download/musl-libc) for CentOS 7. I have reverted this back to `-buster` image.
- This is the …
=> HDDS-6524. Bump rocksdb ldb to 7.0.4 and others in ozone-runner; Reduce image size by ~20%

Dockerfile
I added `httpfs` user and group to this image, so the secure httpfs smoke tests will be able to run, as the Kerberos setup will work.
https://issues.apache.org/jira/browse/HDDS-7720
Built the image locally with my change and used that with Ozone.
=> HDDS-7720. Create httpfs user and group

.github/workflows/build.yaml, Dockerfile
Ubuntu 18.04 runners no longer exist, upgrading them to ubuntu-latest should fix this issue.
[HDDS-8523](https://issues.apache.org/jira/browse/HDDS-8523)
There is a cross-blocking issue here where the automatic workflow won't run with ubuntu 18.04 version because github runners no longer use it, but I can't fix that problem until this issue is fixed.
An example of a workflow run where both issues have been fixed and it worked properly:
https://github.com/Galsza/ozone-docker-runner/actions/runs/4870673262
=> HDDS-8523. Upgrade Github Actions runner to ubuntu-latest

Dockerfile
Adding the openssl command to the base docker image will allow testing certificate related cases. 
[HDDS-8488](https://issues.apache.org/jira/browse/HDDS-8488)
Build the docker image locally and tested it first based on the dockerfile. Then paired it with ozone and all containers were able to run openssl.
=> HDDS-8488. Install openssl in runner image

Dockerfile
* Install `lsof` and `netstat` to help checking network connections
* Sort packages in `yum install` command in the Dockerfile
https://issues.apache.org/jira/browse/HDDS-8628
https://github.com/adoroszlai/ozone-docker-runner/actions/runs/4983558872/jobs/8920739570#step:3:1161
=> HDDS-8628. Install lsof and netstat in ozone-runner

Dockerfile
Bump up rocksdb version in Ozone docker runner
https://issues.apache.org/jira/browse/HDDS-8843
Building locally
=> HDDS-8843. Bump up rocksdb version in Ozone docker runner

.github/workflows/build.yaml
Upgrade GitHub actions to `v4` to get Node.js 20.
https://issues.apache.org/jira/browse/HDDS-10199
CI:
https://github.com/adoroszlai/ozone-docker-runner/actions/runs/7644627140
=> HDDS-10199. Node.js 16 actions are deprecated

Dockerfile
Install OpenJDK 17.0.2 in `ozone-runner` image.
https://issues.apache.org/jira/browse/HDDS-8247
Built the image locally, verified java version:
```
$ docker builder build -t apache/ozone-runner:HDDS-8247 .
...
=> => writing image sha256:abf1973091911ecade064d0e6a8924db5d170879efd079e51c83afc98ac1fbf6                                                                                                                  0.0s
=> => naming to docker.io/apache/ozone-runner:HDDS-8247                                                                                                                                                      0.0s
$ docker run -it --rm apache/ozone-runner:HDDS-8247 java -version
To use Ozone please mount ozone folder to /opt/hadoop
openjdk version "17.0.2" 2022-01-18
OpenJDK …
```
=> HDDS-8247. Bump JDK to 17.0.2

Dockerfile
CentOS 7 has reached EOL on June 30th, Need to adopt alternative Open source Linux Distros.
https://issues.apache.org/jira/browse/HDDS-11143
Manually build the repo, works.
=> HDDS-11143. Switch to Rocky Linux 8 as CentOS 7 is EOL

Dockerfile
`ps` is required for `compatibility` tests:
https://github.com/apache/ozone/blob/c05227a0dc1ba833383ece7379d8a1e977c5bb45/hadoop-ozone/dist/src/main/smoketest/lib/os.robot#L66C1-L67C1
but it's missing from the new Rocky Linux-based image `20240712-jdk17-1`:
`/bin/sh: ps: command not found`
https://issues.apache.org/jira/browse/HDDS-11165
```
$ docker build -t ozone-runner:dev .
...
$ docker run -it --rm ozone-runner:dev ps
To use Ozone please mount ozone folder to /opt/hadoop
PID TTY          TIME CMD
7 pts/0    00:00:00 ps
```
=> HDDS-11165. Install ps in ozone-runner image

Dockerfile
`ldb` was added to `ozone-runner` in HDDS-3859.  It was required at the time for automating a step of the upgrade from 0.5.0 to 1.0.0 (HDDS-3499).
Since `ldb` is no longer needed by recent Ozone versions, I think it is time to remove it from `ozone-runner`.
1. `ldb` is a 286MB binary, increasing downloads for each CI run
2. build take a long time (relative to building the rest of the `ozone-runner` image)
It still can be run using previous versions of the image, if needed.
Additional minor improvements to reduce size:
- EPEL 7 is not needed for Rocky Linux 8
- combine copy and chmod in single `RUN` step
- create users in a loop
https://issues.apache.org/jira/browse/HDDS-11202
Built locally, ran some Ozone acceptance tests (`upgrade`, `ozonesecure-ha`).
Size reduction:
```
REPOSITORY …
```
=> HDDS-11202. Reduce ozone-runner image size

Dockerfile
Current `ozone-runner` comes with JDK 17 (HDDS-8247).
Existing `ozone` images (up to 1.4.0) ship with some outdated software that we'd like to upgrade (e.g. Robot Framework).  However, those Ozone versions do not work with JDK 17.
So we should create `ozone-runner` image with up-to-date software, but with JDK 11 (like before HDDS-8247), in addition to the newer JDK version(s).
https://issues.apache.org/jira/browse/HDDS-11111
Built locally, verified Java version.
```
$ docker builder build -t apache/ozone-runner:HDDS-11111 .
...
$ docker run -it --rm apache/ozone-runner:HDDS-11111 java -version
To use Ozone please mount ozone folder to /opt/hadoop
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode) …
```
=> HDDS-11111. Create ozone-runner base image for Java 11

Dockerfile
The `ozone` command shows a `tput: command not found` error
```bash
rpatel@Rishabhs-MacBook-Pro ozone % docker-compose exec scm bash
bash-4.4$ ozone
Usage: ozone [OPTIONS] SUBCOMMAND [SUBCOMMAND OPTIONS]
OPTIONS is none or any of:
/opt/hadoop/bin/../libexec/ozone-functions.sh: line 413: tput: command not found
--buildpaths                       attempt to add class files from build tree
--config dir                       Ozone config directory
```
The `tput` command is not available
```bash
bash-4.4$ tput
bash: tput: command not found
bash-4.4$ dnf list installed | grep ncurses
ncurses-base.noarch                6.1-10.20180224.el8                    @System   
ncurses-libs.x86_64                6.1-10.20180224.el8                    @System   
```
Installing the ncurses package fixes the …
=> HDDS-11602. Install ncurses to get the tput command

.github/workflows/build.yaml
Add steps to build multi-platform `ozone-runner` images with `linux/amd64` and `linux/arm64`.
https://issues.apache.org/jira/browse/HDDS-8569
Verified that the [image](https://github.com/adoroszlai/ozone-docker-runner/pkgs/container/ozone-runner/301713930?tag=07b14f6d4a4861971054865fa683559f67a7e4cf) built on `push` of this branch to my fork has both architectures.
=> HDDS-8569. Build and publish ozone-runner for linux/arm64

.github/workflows/build-and-tag.yaml
Publish `ozone-runner` Docker images created by the CI workflow to Docker Hub, in addition to existing practice.
Only publish images with tags, not by Git commit SHA (the latter is used only for GitHub Container Registry).
Publishing to Docker Hub is optional, only done if the secrets are defined for the repo.  This way the workflow is still functional in forks whose owners have not set up Docker Hub repository.  ([Example run](https://github.com/adoroszlai/ozone-docker-runner/actions/runs/11708712290/job/32611216489) before I set up secrets in my fork.)
https://issues.apache.org/jira/browse/HDDS-11634
```
git tag test-HDDS-11634
git push adoroszlai test-HDDS-11634
```
[Workflow](https://github.com/adoroszlai/ozone-docker-runner/actions/runs/11720643164/job/32646418482) published the …
=> HDDS-11634. Publish images to Docker Hub from GitHub workflow

Dockerfile
This PR adds the [rclone tool](https://rclone.org/s3/) needed for robot tests
https://issues.apache.org/jira/browse/HDDS-5045
Please replace this section with the link to the Apache JIRA)
CI: https://github.com/ptlrs/ozone-docker-runner/actions/runs/12306659392
Manually built and ran the dev image
=> HDDS-5045. Add rclone package for robot test

Dockerfile
Bump dependencies:
- async profiler 2.9
- awscli 1.37 (latest version)
https://issues.apache.org/jira/browse/HDDS-12359
```
#20 7.998 Successfully installed PyYAML-6.0.2 awscli-1.37.21 boto3-1.36.21 botocore-1.36.21 colorama-0.4.6 docutils-0.16 jmespath-1.0.1 pyasn1-0.6.1 python-dateutil-2.9.0.post0 robotframework-6.1.1 rsa-4.7.2 s3transfer-0.11.2 six-1.17.0 urllib3-1.26.20
...
#23 0.390 + mv async-profiler-2.9-linux-x64 /opt/profiler
```
https://github.com/adoroszlai/ozone-docker-runner/actions/runs/13377374876/job/37359340791#step:7:1137
=> HDDS-12359. Bump async profiler to 2.9, awscli to 1.37

.dockerignore, CONTRIBUTING.md, README.md, build.sh
Add `build.sh`, helper script for building the image.
Benefits:
- consistent experience across `ozone-docker*` repos
- future improvements possible without updating docs
Also add `.dockerignore`.
https://issues.apache.org/jira/browse/HDDS-12441
```bash
$ ./build.sh
...
=> => naming to docker.io/apache/ozone-runner:dev
```
CI:
https://github.com/adoroszlai/ozone-docker-runner/actions/runs/13583576812
=> HDDS-12441. Add helper script for building Docker image

Dockerfile
HDDS-12631. Correct LD_LIBRARY_PATH for ozone-runner Docker image
https://issues.apache.org/jira/browse/HDDS-12631
built a dev ozone-docker-runner image, and built a dev ozone-docker image. Loaded the tests and passed.
=> HDDS-12631. Correct LD_LIBRARY_PATH for ozone-runner Docker image

CONTRIBUTING.md
While testing [HDDS-12499](https://issues.apache.org/jira/browse/HDDS-12499), some deviations from the testing instructions in CONTRIBUTING.md were necessary to get a successful Ozone CI run. This PR proposes to make them official:
- Fix a trivial typo in the image reference.
- Update the instruction on changing the image reference, in line with [HDDS-11813](https://issues.apache.org/jira/browse/HDDS-11813) moving it to check.yml.
- Update the commit hash the pom.xml link points to. (Rationale: check.yml does not exist in the original commit, so that link has to be updated. This point restores consistency.)
https://issues.apache.org/jira/browse/HDDS-12647
- CI: https://github.com/octachoron/ozone-docker-runner/actions/runs/13955519342
- Ozone CI run after following the testing …
=> HDDS-12647. Update testing instructions

Dockerfile
Instead of always installing the latest versions of awscli and boto3 into the images at build time, select specifically the latest versions as of the time this change was made. As noted on [HDDS-12499](https://issues.apache.org/jira/browse/HDDS-12499), this avoids unexpected version changes.
Both packages support Python 3.9, and their dependency declarations are compatible.
https://issues.apache.org/jira/browse/HDDS-12499
- CI on fork: https://github.com/octachoron/ozone-docker-runner/actions/runs/13951576627
- Ozone CI with changed image: https://github.com/octachoron/ozone/actions/runs/13955751134
=> HDDS-12499. Install specific version of awscli and boto3

Dockerfile
Have hadoop native library installed. 
(Please fill in changes proposed in this fix)
https://issues.apache.org/jira/browse/HDDS-12804
Test locally with "docker buildx build" command.
=> HDDS-12804. Include Hadoop native library libhadoop.so

Dockerfile
Rclone Client Test fails with v1.70.1, included in ozone-runner 20250624-1-jdk21:
```
S3: PutObject, compute input header checksum failed, unseekable stream is not supported without TLS and trailing checksum
```
Install v1.69.3 instead of "latest".
https://issues.apache.org/jira/browse/HDDS-13333
```
$ ./build.sh
...
naming to docker.io/apache/ozone-runner:dev
```
Ran `s3/rclone.robot` in `ozonesecure` environment.
CI:
https://github.com/adoroszlai/ozone-docker-runner/actions/runs/15870072547
=> HDDS-13333. Downgrade rclone to 1.69

Dockerfile
Apache Ozone presently utilizes `goofys` as its S3 FUSE implementation. Given that the `goofys` repository has been forked and is now under the maintenance of StatCan, our intention is to transition to `mountpoint-s3`, an AWS Labs-maintained package, for subsequent development efforts.
https://issues.apache.org/jira/browse/HDDS-13446
```
$ ./build.sh
...
$ docker run -it --rm apache/ozone-runner:dev bash
[hadoop@e9911f14f942 ~]$ which mount-s3
/usr/bin/mount-s3
[hadoop@e9911f14f942 ~]$ which goofys
/usr/bin/which: no goofys in 
```
CI: https://github.com/echonesis/ozone-docker-runner/actions/runs/16337455101
=> HDDS-13446. Replace goofys with mountpoint-s3 in ozone-docker-runner
